### ISSUE TITLE
termination_measure enum value converted to numpy array causes compilation assertion error

### ISSUE THREAD

**Issue by davidt0x** [PrincetonUniversity/PsyNeuLink#2984] opened 2024-06-24 17:17 UTC
Current version of devel has a bug where `termination_measure=pnl.TimeScale.TRIAL` on the LCAMechanism gets converted to a numpy array somewhere, which leads to an assertion error in compilation. See [Scripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py](https://github.com/PrincetonUniversity/PsyNeuLink/blob/devel/Scripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py) for an example reproducing this problem. This seems to only occur when the composition is run within the PEC and not when it is run by itself. @kmantel, do you think this is related to changes you have been working with the numpy conversion?

**Comment by kmantel** [comment] 2024-06-25 00:27
It seems very likely. I'm sure why it wouldn't be happening outside of a PEC though. I'll check it out

**Comment by kmantel** [comment] 2024-06-25 05:16
It's related to syncing the termination_measure values between compiled/non-compiled. There was a commit that removed a filter stopping termination_measure from being synced I believe. termination_measure is stored as an int in the compiled structs, and this was getting written back to the non-compiled side to allow the sync. This

```diff
diff --git a/psyneulink/core/components/mechanisms/processing/transfermechanism.py b/psyneulink/core/components/mechanisms/processing/transfermechanism.py
index e2dedd3d30..d02d8e1c2a 100644
--- a/psyneulink/core/components/mechanisms/processing/transfermechanism.py
+++ b/psyneulink/core/components/mechanisms/processing/transfermechanism.py
@@ -1598,9 +1598,13 @@ class TransferMechanism(ProcessingMechanism_Base):
 
             builder.call(func, [func_params, func_state, func_in, cmp_val_ptr])
 
-        elif isinstance(self.termination_measure, TimeScale):
+        elif isinstance(self.termination_measure, TimeScale) or self.termination_measure in {ts.value for ts in TimeScale}:
+            if isinstance(self.termination_measure, TimeScale):
+                measure = self.termination_measure.value
+            else:
+                measure = self.termination_measure
             num_executions_array_ptr = ctx.get_param_or_state_ptr(builder, self, "num_executions", state_struct_ptr=m_state)
-            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(self.termination_measure.value)])
+            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(measure)])
             elem_val = builder.sitofp(builder.load(elem_ptr), threshold.type)
             builder.store(elem_val, cmp_val_ptr)
```

is a clunky way of handling the error for a script like that, but I'm not sure what the best way is to deal with cases like this where the compiled side needs data in format different than the non-compiled side.

**Comment by jdcpni** [comment] 2024-06-25 12:46
We should bring this up at today’s meeting.

jdc



On Jun 25, 2024, at 1:16 AM, kmantel ***@***.***> wrote:



It's related to syncing the termination_measure values between compiled/non-compiled. There was a commit that removed a filter stopping termination_measure from being synced I believe. termination_measure is stored as an int in the compiled structs, and this was getting written back to the non-compiled side to allow the sync. This

diff --git a/psyneulink/core/components/mechanisms/processing/transfermechanism.py b/psyneulink/core/components/mechanisms/processing/transfermechanism.py
index e2dedd3d30..d02d8e1c2a 100644
--- a/psyneulink/core/components/mechanisms/processing/transfermechanism.py
+++ b/psyneulink/core/components/mechanisms/processing/transfermechanism.py
@@ -1598,9 +1598,13 @@ class TransferMechanism(ProcessingMechanism_Base):

             builder.call(func, [func_params, func_state, func_in, cmp_val_ptr])

-        elif isinstance(self.termination_measure, TimeScale):
+        elif isinstance(self.termination_measure, TimeScale) or self.termination_measure in {ts.value for ts in TimeScale}:
+            if isinstance(self.termination_measure, TimeScale):
+                measure = self.termination_measure.value
+            else:
+                measure = self.termination_measure
             num_executions_array_ptr = ctx.get_param_or_state_ptr(builder, self, "num_executions", state_struct_ptr=m_state)
-            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(self.termination_measure.value)])
+            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(measure)])
             elem_val = builder.sitofp(builder.load(elem_ptr), threshold.type)
             builder.store(elem_val, cmp_val_ptr)

is a clunky way of handling the error for a script like that, but I'm not sure what the best way is to deal with cases like this where the compiled side needs data in format different than the non-compiled side.

**Comment by jvesely** [comment] 2024-06-25 19:23
> It's related to syncing the termination_measure values between compiled/non-compiled. There was a commit that removed a filter stopping termination_measure from being synced I believe. termination_measure is stored as an int in the compiled structs, and this was getting written back to the non-compiled side to allow the sync. This
> 
> ```diff
> diff --git a/psyneulink/core/components/mechanisms/processing/transfermechanism.py b/psyneulink/core/components/mechanisms/processing/transfermechanism.py
> index e2dedd3d30..d02d8e1c2a 100644
> --- a/psyneulink/core/components/mechanisms/processing/transfermechanism.py
> +++ b/psyneulink/core/components/mechanisms/processing/transfermechanism.py
> @@ -1598,9 +1598,13 @@ class TransferMechanism(ProcessingMechanism_Base):
>  
>              builder.call(func, [func_params, func_state, func_in, cmp_val_ptr])
>  
> -        elif isinstance(self.termination_measure, TimeScale):
> +        elif isinstance(self.termination_measure, TimeScale) or self.termination_measure in {ts.value for ts in TimeScale}:
> +            if isinstance(self.termination_measure, TimeScale):
> +                measure = self.termination_measure.value
> +            else:
> +                measure = self.termination_measure
>              num_executions_array_ptr = ctx.get_param_or_state_ptr(builder, self, "num_executions", state_struct_ptr=m_state)
> -            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(self.termination_measure.value)])
> +            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(measure)])
>              elem_val = builder.sitofp(builder.load(elem_ptr), threshold.type)
>              builder.store(elem_val, cmp_val_ptr)
> ```
> 
> is a clunky way of handling the error for a script like that, but I'm not sure what the best way is to deal with cases like this where the compiled side needs data in a format different than the non-compiled side.

I think the patch mostly works as a targeted fix. Can you change the measure value extraction to:
```
measure = getarr(self.termination_measure, "value", self.termination_measure)
```
that should save a repeated call to `isinstance`.

**Comment by kmantel** [comment] 2024-06-25 20:29
Yeah, no problem. I was mostly using it to explain and didn't put a ton of thought into it. If there's a more preferred way of doing a one-off fix here that's fine by me.

**Comment by jvesely** [comment] 2024-06-25 21:43
> Yeah, no problem. I was mostly using it to explain and didn't put a ton of thought into it. If there's a more preferred way of doing a one-off fix here that's fine by me.

I originally considered just adding a check for  `self.termination_measure.dtype`, but the value check works just as well.
it should be possible to simplify it and only use:
```
# termination_measure can be either a TimeScale value or a numpy 0-d array that corresponds to a TimeScale value
elif self.termination_measure in TimeScale:
```
but I'm unsure which Python version introduced `in Enum` pattern.

**Comment by kmantel** [comment] 2024-06-26 02:34
> > Yeah, no problem. I was mostly using it to explain and didn't put a ton of thought into it. If there's a more preferred way of doing a one-off fix here that's fine by me.
> 
> I originally considered just adding a check for `self.termination_measure.dtype`, but the value check works just as well. it should be possible to simplify it and only use:
> 
> ```
> # termination_measure can be either a TimeScale value or a numpy 0-d array that corresponds to a TimeScale value
> elif self.termination_measure in TimeScale:
> ```
> 
> but I'm unsure which Python version introduced `in Enum` pattern.

I thought to do that, but at least in 3.9 `in Enum` only works for enum values and throws TypeError for ints. It might have been ok if TimeScale were an IntEnum

**Comment by jvesely** [comment] 2024-06-26 16:02
> > > Yeah, no problem. I was mostly using it to explain and didn't put a ton of thought into it. If there's a more preferred way of doing a one-off fix here that's fine by me.
> > 
> > 
> > I originally considered just adding a check for `self.termination_measure.dtype`, but the value check works just as well. it should be possible to simplify it and only use:
> > ```
> > # termination_measure can be either a TimeScale value or a numpy 0-d array that corresponds to a TimeScale value
> > elif self.termination_measure in TimeScale:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but I'm unsure which Python version introduced `in Enum` pattern.
> 
> I thought to do that, but at least in 3.9 `in Enum` only works for enum values and throws TypeError for ints. It might have been ok if TimeScale were an IntEnum

thanks for checking. it looks like it's new in 3.12
```
>>> 1 in foo
<stdin>:1: DeprecationWarning: in 3.12 __contains__ will no longer raise TypeError, but will return True or
False depending on whether the value is a member or the value of a member
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/enum.py", line 742, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'int' and 'EnumType'
```

The original approach with a set should work even without the current instance check:
```
elif self.termination_measure in {ts.value for ts in TimeScale}:
```

**Comment by kmantel** [comment] 2024-07-02 00:00
Also on 3.12 maybe? I tested 3.9 and 3.11:

```
>>> pnl.TimeScale.TRIAL in {ts.value for ts in pnl.TimeScale}
False
```

**Comment by jvesely** [comment] 2024-07-02 02:49
Hm, I think there's a better fix. I'll post it either tonight or tomorrow.

**Comment by davidt0x** [comment] 2024-07-08 14:38
Hey @jvesely and @kmantel,

Sorry for the lack of input on this. I have been out on vacation and then sick for a bit. I tried the [script]([Scripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py](https://github.com/PrincetonUniversity/PsyNeuLink/blob/devel/Scripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py)) again on the latest devel and I am still getting errors: `AssertionError: Not Supported: 2.` 

This is the quick hack fix that I implemented on my latest pec branch to get it working:

```python
        elif isinstance(self.termination_measure, TimeScale) or isinstance(self.termination_measure, np.ndarray) or self.termination_measure in {ts.value for ts in TimeScale}:
            if isinstance(self.termination_measure, TimeScale):
                measure = self.termination_measure.value
            else:
                measure = self.termination_measure
            num_executions_array_ptr = ctx.get_param_or_state_ptr(builder, self, "num_executions", state_struct_ptr=m_state)
            elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(measure)])
            elem_val = builder.sitofp(builder.load(elem_ptr), threshold.type)
            builder.store(elem_val, cmp_val_ptr)
```

It is basically @kmantel's fix but I added a check for np.array since it seems the value can also be a numpy array which isn't hashable.

**Comment by jvesely** [comment] 2024-07-08 14:48
> Hey @jvesely and @kmantel,
> 
> Sorry for the lack of input on this. I have been out on vacation and then sick for a bit. I tried the [script](%5BScripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py%5D(https://github.com/PrincetonUniversity/PsyNeuLink/blob/devel/Scripts/Debug/stability_flexibility/stability_flexibility_pec_fit.py)) again on the latest devel and I am still getting errors: `AssertionError: Not Supported: 2.`
> 
> This is the quick hack fix that I implemented on my latest pec branch to get it working:
> 
> ```python
>         elif isinstance(self.termination_measure, TimeScale) or isinstance(self.termination_measure, np.ndarray) or self.termination_measure in {ts.value for ts in TimeScale}:
>             if isinstance(self.termination_measure, TimeScale):
>                 measure = self.termination_measure.value
>             else:
>                 measure = self.termination_measure
>             num_executions_array_ptr = ctx.get_param_or_state_ptr(builder, self, "num_executions", state_struct_ptr=m_state)
>             elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), ctx.int32_ty(measure)])
>             elem_val = builder.sitofp(builder.load(elem_ptr), threshold.type)
>             builder.store(elem_val, cmp_val_ptr)
> ```
> 
> It is basically @kmantel's fix but I added a check for np.array since it seems the value can also be a numpy array which isn't hashable.

Can you sync with devel and try without any of these changes? this should be fixed.

**Comment by davidt0x** [comment] 2024-07-08 15:10
This is the error I get with latest devel:

```
  File "C:\Dropbox\princeton\PsyNeuLink_Stuff\PsyNeuLink\psyneulink\core\components\mechanisms\processing\transfermechanism.py", line 1619, in _gen_llvm_is_finished_cond
    elem_ptr = builder.gep(num_executions_array_ptr, [ctx.int32_ty(0), index])
  File "C:\Anaconda3\envs\pnl\lib\site-packages\llvmlite\ir\builder.py", line 927, in gep
    instr = instructions.GEPInstr(self.block, ptr, indices,
  File "C:\Anaconda3\envs\pnl\lib\site-packages\llvmlite\ir\instructions.py", line 514, in __init__
    lasttyp, typ = typ, typ.gep(i)
  File "C:\Anaconda3\envs\pnl\lib\site-packages\llvmlite\ir\types.py", line 466, in gep
    raise TypeError(i.type)
TypeError: double
```

Looks like the int is getting converted to a double somewhere when the composition is called within the PEC. Works fine when called stand alone.

**Comment by jvesely** [comment] 2024-07-09 01:58
yeah, the problem is in converting ndarrays to LLVM IR:
```
        elif isinstance(t, np.ndarray):
            return self.convert_python_struct_to_llvm_ir(t.tolist())
```
This tries to reuse the code for converting lists, but it doesn't work for 0-d arrays. 
something like `array(2, dtype=uint32)` turns into `<class 'int'>`  returned from `tolist()`

**Comment by jvesely** [comment] 2024-07-09 16:59
Should be fixed on devel now—this time with a test.

**Closed** 2024-11-12 03:50 UTC
Labels: bug, compiler, fixed-in-devel
