### ISSUE TITLE
Publish only HTML docs corresponding to releases

### ISSUE THREAD

**Issue by mihaic** [PrincetonUniversity/PsyNeuLink#748] opened 2018-04-03 01:29 UTC
The version number shown in the currently published HTML documentation is `0.4.5.2+18`:
https://princetonuniversity.github.io/PsyNeuLink/

As far as I understand, this represents a commit that does not correspond to a release. I think it would be helpful to only publish docs corresponding to releases.

**Comment by kmantel** [comment] 2018-04-11 21:04
In general this should now be true, in that we consider pushes to master to correspond to a release. It's possible that there have been problems with the build server that generates the documentation, because when this issue was posted we had already released v0.4.6.0, and at the moment the version on the docs seems to be correct. I'm going to try to pinpoint the cause of this

**Comment by jvesely** [comment] 2021-02-20 18:45
@kmantel, I think this one should be fixed.
The current script updates `branches/$BRANCH` on push to `master`, `devel`, and `docs` branches.
The root documentation is only updated on tags present on `master`, other pushes to master do not regenerate the root docs (only `branches/master`)

**Comment by jdcpni** [comment] 2021-02-20 23:31
Not sure I a following the consequences of this, but on the last pull to master the main docs do seem to have been updated.


jdc



On Feb 20, 2021, at 1:45 PM, Jan Vesely <notifications@github.com<mailto:notifications@github.com>> wrote:



@kmantel<https://github.com/kmantel>, I think this one should be fixed.
The current script updates branches/$BRANCH on push to master, devel, and docs branches.
The root documentation is only updated on tags present on master, other pushes to master do not regenerate the root docs (only branches/master)

**Comment by kmantel** [comment] 2021-02-22 23:56
> @kmantel, I think this one should be fixed.
> The current script updates `branches/$BRANCH` on push to `master`, `devel`, and `docs` branches.
> The root documentation is only updated on tags present on `master`, other pushes to master do not regenerate the root docs (only `branches/master`)

Checking https://princetonuniversity.github.io/PsyNeuLink/branch/master/, the version is `0.8.5.1+47`, and the version of the parent commit of current master is  `0.8.5.1+46`. I'm guessing the cause of the original problem (if it wasn't entirely before we'd push a new tag on each push to master) was jenkins building docs for the master push before the updated tag was pushed, resulting in the + version in the same way. From what I can see, the Action would handle this. Has the problem happened again?

**Comment by jvesely** [comment] 2021-02-23 14:30
> > @kmantel, I think this one should be fixed.
> > The current script updates `branches/$BRANCH` on push to `master`, `devel`, and `docs` branches.
> > The root documentation is only updated on tags present on `master`, other pushes to master do not regenerate the root docs (only `branches/master`)
> 
> Checking https://princetonuniversity.github.io/PsyNeuLink/branch/master/, the version is `0.8.5.1+47`, and the version of the parent commit of current master is `0.8.5.1+46`. I'm guessing the cause of the original problem (if it wasn't entirely before we'd push a new tag on each push to master) was jenkins building docs for the master push before the updated tag was pushed, resulting in the + version in the same way. From what I can see, the Action would handle this. Has the problem happened again?

The commit ussually comes before the tag, since the commit created on gh and the tag is added after.
Nothing new here, just checking if this can be closed since it looks fixed.

**Comment by kmantel** [comment] 2021-02-23 21:25
Ok, I think we can consider it fixed by #1888.

**Closed by kmantel** 2021-02-23 21:25 UTC
